### ISSUE TITLE
How to setup "find long running threads"

### ISSUE THREAD

**Issue by ultimoamore** [irockel/tda#18]
How can I use "find long running threads"? I don't understand the regular expression I'm supposed to use.
No matter what I do I don't get any result (I can provide the dump in private)

**Comment by irockel** [comment]
TDA had an integrated online help, since the move to github this is broken and I want to merge it into the Github Wiki, but because lack of time I didn't manage to so far. The regular expression is just a normal Java Regular Expression and is matched on the First Line (not just Thread Name). A common mistake is to forget the " in the thread name, so if the thread name is something like AJPWorker-4711, usually something like this is required for regular expression: *``"AJPWorker-4711.*``*.

This is the extracted Doc from the onlinehelp:

> A common usecase for thread dump analysis is the long running thread detection. TDA offers some help for finding these long running threads. The "Find long running threads" option in the tools menu or from the popup menu in the main tree checks for long running threads in marked thread dumps in the main tree. 
> 
> The analysis is quite simple though, it just compares the thread names and if they match adds the thread to the result. A regular expression can be specified for filtering just the interesting threads. The usual filters are also applied to the result view of the analysis to filter out uninteresting threads. For a useful result appropriate filters should be specified to filter out all sleeping and uninteresting threads.
> 
> The long running threads detection is a bit picky about the selected nodes for the detection. You should only select thread dump root nodes otherwise the detection might through an exception as it doesn't know what to do with the selected nodes. You also always should select nodes from one VM run, otherwise you might get quite weird results because the detection matched threads from different VM runs.

Hope this helps.

**Comment by irockel** [comment]
Added Wiki-Page for this:

**Comment by ultimoamore** [comment]
Thank you very much for the reply; I'm sorry but I can't seem to get it working. Can I send you 2 dumps in private?

**Comment by irockel** [comment]
Maybe you can post a thread header you want to match and the expression you use.
